from setuptools import setup, find_packages
from torch.utils.cpp_extension import BuildExtension, CUDAExtension

setup(name='dnls',
      package_dir={"": "lib"},
      packages=find_packages("."),
      package_data={'': ['*.so']},
      include_package_data=True,
      ext_modules=[
          CUDAExtension('dnls_cuda', [
              'lib/csrc/nn/pfc.cpp',
              'lib/csrc/nn/pfc_kernel.cu',
              'lib/csrc/nn/temporal_inds.cpp',
              'lib/csrc/nn/temporal_inds_kernel.cu',
              'lib/csrc/nn/accumulate_flow.cpp',
              'lib/csrc/nn/accumulate_flow_kernel.cu',
              'lib/csrc/nn/interpolate_inds.cpp',
              'lib/csrc/nn/interpolate_inds_kernel.cu',
              'lib/csrc/nn/unique_topk.cpp',
              'lib/csrc/nn/unique_topk_kernel.cu',
              'lib/csrc/nn/anchor_self.cpp',
              'lib/csrc/nn/anchor_self_kernel.cu',
              'lib/csrc/nn/jitter_unique_inds.cpp',
              'lib/csrc/nn/jitter_unique_inds_kernel.cu',
              'lib/csrc/search/search_with_heads.cpp',
              'lib/csrc/search/search_with_heads_kernel.cu',
              'lib/csrc/search/prod_dists.cpp',
              'lib/csrc/search/prod_dists_kernel.cu',
              'lib/csrc/search/prod_refine.cpp',
              'lib/csrc/search/prod_refine_kernel.cu',
              'lib/csrc/search/prod_with_index_cuda.cpp',
              'lib/csrc/search/prod_with_index_kernel.cu',
              'lib/csrc/search/prod_pf_with_index_cuda.cpp',
              'lib/csrc/search/prod_pf_with_index_kernel.cu',
              'lib/csrc/search/l2_cuda.cpp',
              'lib/csrc/search/l2_kernel.cu',
              'lib/csrc/search/l2_dists_cuda.cpp',
              'lib/csrc/search/l2_dists_kernel.cu',
              'lib/csrc/search/l2_with_index_cuda.cpp',
              'lib/csrc/search/l2_with_index_kernel.cu',
              'lib/csrc/search/l2_search_with_heads.cpp',
              'lib/csrc/search/l2_search_with_heads_kernel.cu',
              'lib/csrc/search/window_search.cpp',
              'lib/csrc/search/window_search_kernel.cu',
              'lib/csrc/search/prod_cuda.cpp',
              'lib/csrc/search/prod_kernel.cu',
              'lib/csrc/search/prod_search_with_heads.cpp',
              'lib/csrc/search/prod_search_with_heads_kernel.cu',
              # 'lib/csrc/search/prod_search_patches_with_heads.cpp',
              # 'lib/csrc/search/prod_search_patches_with_heads_kernel.cu',
              'lib/csrc/tile_k/foldk_cuda.cpp',
              'lib/csrc/tile_k/foldk_kernel.cu',
              'lib/csrc/tile_k/unfoldk_cuda.cpp',
              'lib/csrc/tile_k/unfoldk_kernel.cu',
              'lib/csrc/tile/fold_cuda.cpp',
              'lib/csrc/tile/fold_kernel.cu',
              'lib/csrc/tile/ifold_cuda.cpp',
              'lib/csrc/tile/ifold_kernel.cu',
              'lib/csrc/tile/ifoldz_cuda.cpp',
              'lib/csrc/tile/ifoldz_kernel.cu',
              'lib/csrc/tile/unfold_cuda.cpp',
              'lib/csrc/tile/unfold_kernel.cu',
              'lib/csrc/tile/iunfold_cuda.cpp',
              'lib/csrc/tile/iunfold_kernel.cu',
              'lib/csrc/reducers/wpsum_cuda.cpp',
              'lib/csrc/reducers/wpsum_kernel.cu',
              'lib/csrc/reducers/iwpsum_cuda.cpp',
              'lib/csrc/reducers/iwpsum_kernel.cu',
              'lib/csrc/reducers/wpsum_heads_cuda.cpp',
              'lib/csrc/reducers/wpsum_heads_kernel.cu',
              'lib/csrc/reducers/wpsum_heads_2vid_cuda.cpp',
              'lib/csrc/reducers/wpsum_heads_2vid_kernel.cu',
              'lib/csrc/pybind.cpp',
          ],
          )
      ],
      cmdclass={'build_ext': BuildExtension},
)

