name: Button Pytest

on:
    workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["3.10"]
        cuda-version: ["11.3"]
    steps:
    - name: Cache Cuda Modules
      id: cache-cuda
      uses: actions/cache@v3
      env:
        cache-name: cache-cuda-toolkit
      with:
        # cuda cache files are stored in `/usr/local/cuda/` on Linux/macOS
        path: |
          /usr/local/cuda*
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@master
      with:
        # ninja version to download. Default: 1.10.0
        version: 1.10.0
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - if: ${{ steps.cache-cuda-toolkit.outputs.cache-hit != 'true' }}
      name: Install CUDA
      continue-on-error: true
      uses: Jimver/cuda-toolkit@v0.2.8
      id: cuda-toolkit
      with:
        cuda: '11.3.0'
    - name: Export CUDA Paths
      run: |
        export CUDA_PATH=/usr/bin/cuda-11.3/
        export PATH="$CUDA_PATH/bin:$PATH"
        export LD_LIBRARY_PATH="/usr/local/cuda-11.3/lib64:$LD_LIBRARY_PATH"
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r reqs/reqs_cu113.txt
    - name: Install our package
      run: |
        python -m pip install .
    - name: Testing Code
      run: |
        python -m pytest -s ./test/

  
