name: Button Pytest

on:
    workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        python-version: ["3.8"]
        cuda-version: ["11.1"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: CUDA Install ${{ matrix.cuda-version }}
      if: ${{ matrix.cuda-version != 'cpu' }}
      run: |
        bash .github/workflows/install_cuda.sh
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Install our package
      run: |
        python -m pip install ./lib
    - name: Testing Code
      run: |
        python -m pytest -s ./test/

  
